SIDO_DICT = {"서울특별시": "Seoul",
             "강원도": "Gangwon",
             "경기도": "Gyeonggi",
             "경상남도": "SouthGyeongsang",
             '경상북도': "NorthGyeongsang",
             "광주광역시": "Gwangju",
             "대구광역시": "Daegu",
             "대전광역시": "Daejeon",
             "부산광역시": "Busan",
             "세종특별자치시": "Sejong",
             "울산광역시": "Ulsan",
             "전라남도": "SouthJeolla",
             "전라북도": "NorthJeolla",
             "제주특별자치도": "Jeju",
             "충청남도": "SouthChungcheong",
             "충청북도": "NorthChungcheong",
             "인천광역시": "Incheon"}